Megatron-Deepspeed GPT
GoogleCloudPlatform/llm-pipeline-examples pull request #27
Opened 2023-05-05 22:52 UTC by abdallag

2023-05-11 17:08 UTC, Chris113113 requested changes

2023-05-11 17:34 UTC, abdallag commented on docker/gpt/train.Dockerfile
> +RUN sudo apt install ninja-build
Done

2023-05-11 17:35 UTC, abdallag commented on scripts/gpt/gpt.sh
> +#GLOBAL_BATCH=$(( ${GPN} * ${MICRO_BATCH} * ${NODES} ))
Removed

2023-05-11 17:35 UTC, abdallag commented on scripts/gpt/gpt.sh
> +#OUTPUT_DIR=baseline_nl${NLAYERS}_hs${HIDDEN}_gb${GLOBAL_BATCH}_mb${MICRO_BATCH}
Removed

2023-05-11 18:38 UTC, Chris113113 submitted a review, later dismissed

2023-05-18 20:24 UTC, Chris113113 approved these changes

2023-05-18 20:27 UTC, merged