Add GKE Inferencing quickstart guide, and clarify some docs
GoogleCloudPlatform/llm-pipeline-examples pull request #55
Opened 2023-07-05 20:59 UTC by Chris113113

2023-07-11 21:05 UTC, abdallag requested changes

2023-07-12 17:40 UTC, Chris113113 commented on examples/inferencing/running-on-gke.md
>      $ gcloud containers clusters get-credentials $CLUSTER_NAME --region $REGION --project $PROJECT
Fixed

2023-07-12 17:40 UTC, Chris113113 commented on examples/inferencing/running-on-gke.md
> +The result of these commands will create a 2 node GKE cluster with a2-megagpu-16g VMs, and 4 nvidia-tesla-a100 GPUs on each node.
Fixed

2023-07-12 21:53 UTC, abdallag requested changes

2023-07-12 21:53 UTC, abdallag commented on examples/inferencing/running-on-gke.md
>  Sample output:
A few issues when trying to deploy the notebook:
1. Notebooks APIs are not enabled by default. Let's add them to the services being enabled in the beginning.
2. Let's replace <project_id> with the project ID where the image is running

Also, let's replace <your_payload_goes_here> with a default payload the user can test with.

2023-07-13 16:58 UTC, abdallag approved these changes

2023-07-13 17:41 UTC, merged